/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as RoomsAccessLinkRouteImport } from './routes/rooms/access-link'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms/$roomId'
import { Route as V1StartupIndexRouteImport } from './routes/v1/startup/index'
import { Route as V1ReadinessIndexRouteImport } from './routes/v1/readiness/index'
import { Route as V1LivenessIndexRouteImport } from './routes/v1/liveness/index'
import { Route as UseCasesTemplatesIndexRouteImport } from './routes/use-cases/templates/index'
import { Route as UseCasesStandaloneIndexRouteImport } from './routes/use-cases/standalone/index'
import { Route as UseCasesTemplatesInstanceIdRouteImport } from './routes/use-cases/templates/$instanceId'
import { Route as UseCasesStandaloneInstanceIdRouteImport } from './routes/use-cases/standalone/$instanceId'
import { Route as ApiAiChatsChatIdRouteImport } from './routes/api/ai/chats/$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsAccessLinkRoute = RoomsAccessLinkRouteImport.update({
  id: '/rooms/access-link',
  path: '/rooms/access-link',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1StartupIndexRoute = V1StartupIndexRouteImport.update({
  id: '/v1/startup/',
  path: '/v1/startup/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ReadinessIndexRoute = V1ReadinessIndexRouteImport.update({
  id: '/v1/readiness/',
  path: '/v1/readiness/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1LivenessIndexRoute = V1LivenessIndexRouteImport.update({
  id: '/v1/liveness/',
  path: '/v1/liveness/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesTemplatesIndexRoute = UseCasesTemplatesIndexRouteImport.update({
  id: '/use-cases/templates/',
  path: '/use-cases/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesStandaloneIndexRoute = UseCasesStandaloneIndexRouteImport.update({
  id: '/use-cases/standalone/',
  path: '/use-cases/standalone/',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesTemplatesInstanceIdRoute =
  UseCasesTemplatesInstanceIdRouteImport.update({
    id: '/use-cases/templates/$instanceId',
    path: '/use-cases/templates/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UseCasesStandaloneInstanceIdRoute =
  UseCasesStandaloneInstanceIdRouteImport.update({
    id: '/use-cases/standalone/$instanceId',
    path: '/use-cases/standalone/$instanceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiChatsChatIdRoute = ApiAiChatsChatIdRouteImport.update({
  id: '/api/ai/chats/$chatId',
  path: '/api/ai/chats/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/access-link': typeof RoomsAccessLinkRoute
  '/error/': typeof ErrorIndexRoute
  '/use-cases/standalone/$instanceId': typeof UseCasesStandaloneInstanceIdRoute
  '/use-cases/templates/$instanceId': typeof UseCasesTemplatesInstanceIdRoute
  '/use-cases/standalone/': typeof UseCasesStandaloneIndexRoute
  '/use-cases/templates/': typeof UseCasesTemplatesIndexRoute
  '/v1/liveness/': typeof V1LivenessIndexRoute
  '/v1/readiness/': typeof V1ReadinessIndexRoute
  '/v1/startup/': typeof V1StartupIndexRoute
  '/api/ai/chats/$chatId': typeof ApiAiChatsChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/access-link': typeof RoomsAccessLinkRoute
  '/error': typeof ErrorIndexRoute
  '/use-cases/standalone/$instanceId': typeof UseCasesStandaloneInstanceIdRoute
  '/use-cases/templates/$instanceId': typeof UseCasesTemplatesInstanceIdRoute
  '/use-cases/standalone': typeof UseCasesStandaloneIndexRoute
  '/use-cases/templates': typeof UseCasesTemplatesIndexRoute
  '/v1/liveness': typeof V1LivenessIndexRoute
  '/v1/readiness': typeof V1ReadinessIndexRoute
  '/v1/startup': typeof V1StartupIndexRoute
  '/api/ai/chats/$chatId': typeof ApiAiChatsChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
  '/rooms/access-link': typeof RoomsAccessLinkRoute
  '/error/': typeof ErrorIndexRoute
  '/use-cases/standalone/$instanceId': typeof UseCasesStandaloneInstanceIdRoute
  '/use-cases/templates/$instanceId': typeof UseCasesTemplatesInstanceIdRoute
  '/use-cases/standalone/': typeof UseCasesStandaloneIndexRoute
  '/use-cases/templates/': typeof UseCasesTemplatesIndexRoute
  '/v1/liveness/': typeof V1LivenessIndexRoute
  '/v1/readiness/': typeof V1ReadinessIndexRoute
  '/v1/startup/': typeof V1StartupIndexRoute
  '/api/ai/chats/$chatId': typeof ApiAiChatsChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rooms/$roomId'
    | '/rooms/access-link'
    | '/error/'
    | '/use-cases/standalone/$instanceId'
    | '/use-cases/templates/$instanceId'
    | '/use-cases/standalone/'
    | '/use-cases/templates/'
    | '/v1/liveness/'
    | '/v1/readiness/'
    | '/v1/startup/'
    | '/api/ai/chats/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rooms/$roomId'
    | '/rooms/access-link'
    | '/error'
    | '/use-cases/standalone/$instanceId'
    | '/use-cases/templates/$instanceId'
    | '/use-cases/standalone'
    | '/use-cases/templates'
    | '/v1/liveness'
    | '/v1/readiness'
    | '/v1/startup'
    | '/api/ai/chats/$chatId'
  id:
    | '__root__'
    | '/'
    | '/rooms/$roomId'
    | '/rooms/access-link'
    | '/error/'
    | '/use-cases/standalone/$instanceId'
    | '/use-cases/templates/$instanceId'
    | '/use-cases/standalone/'
    | '/use-cases/templates/'
    | '/v1/liveness/'
    | '/v1/readiness/'
    | '/v1/startup/'
    | '/api/ai/chats/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
  RoomsAccessLinkRoute: typeof RoomsAccessLinkRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  UseCasesStandaloneInstanceIdRoute: typeof UseCasesStandaloneInstanceIdRoute
  UseCasesTemplatesInstanceIdRoute: typeof UseCasesTemplatesInstanceIdRoute
  UseCasesStandaloneIndexRoute: typeof UseCasesStandaloneIndexRoute
  UseCasesTemplatesIndexRoute: typeof UseCasesTemplatesIndexRoute
  V1LivenessIndexRoute: typeof V1LivenessIndexRoute
  V1ReadinessIndexRoute: typeof V1ReadinessIndexRoute
  V1StartupIndexRoute: typeof V1StartupIndexRoute
  ApiAiChatsChatIdRoute: typeof ApiAiChatsChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/access-link': {
      id: '/rooms/access-link'
      path: '/rooms/access-link'
      fullPath: '/rooms/access-link'
      preLoaderRoute: typeof RoomsAccessLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/startup/': {
      id: '/v1/startup/'
      path: '/v1/startup'
      fullPath: '/v1/startup/'
      preLoaderRoute: typeof V1StartupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/readiness/': {
      id: '/v1/readiness/'
      path: '/v1/readiness'
      fullPath: '/v1/readiness/'
      preLoaderRoute: typeof V1ReadinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/liveness/': {
      id: '/v1/liveness/'
      path: '/v1/liveness'
      fullPath: '/v1/liveness/'
      preLoaderRoute: typeof V1LivenessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/templates/': {
      id: '/use-cases/templates/'
      path: '/use-cases/templates'
      fullPath: '/use-cases/templates/'
      preLoaderRoute: typeof UseCasesTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/standalone/': {
      id: '/use-cases/standalone/'
      path: '/use-cases/standalone'
      fullPath: '/use-cases/standalone/'
      preLoaderRoute: typeof UseCasesStandaloneIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/templates/$instanceId': {
      id: '/use-cases/templates/$instanceId'
      path: '/use-cases/templates/$instanceId'
      fullPath: '/use-cases/templates/$instanceId'
      preLoaderRoute: typeof UseCasesTemplatesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases/standalone/$instanceId': {
      id: '/use-cases/standalone/$instanceId'
      path: '/use-cases/standalone/$instanceId'
      fullPath: '/use-cases/standalone/$instanceId'
      preLoaderRoute: typeof UseCasesStandaloneInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chats/$chatId': {
      id: '/api/ai/chats/$chatId'
      path: '/api/ai/chats/$chatId'
      fullPath: '/api/ai/chats/$chatId'
      preLoaderRoute: typeof ApiAiChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomsRoomIdRoute: RoomsRoomIdRoute,
  RoomsAccessLinkRoute: RoomsAccessLinkRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  UseCasesStandaloneInstanceIdRoute: UseCasesStandaloneInstanceIdRoute,
  UseCasesTemplatesInstanceIdRoute: UseCasesTemplatesInstanceIdRoute,
  UseCasesStandaloneIndexRoute: UseCasesStandaloneIndexRoute,
  UseCasesTemplatesIndexRoute: UseCasesTemplatesIndexRoute,
  V1LivenessIndexRoute: V1LivenessIndexRoute,
  V1ReadinessIndexRoute: V1ReadinessIndexRoute,
  V1StartupIndexRoute: V1StartupIndexRoute,
  ApiAiChatsChatIdRoute: ApiAiChatsChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
