#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
#
# SPDX-License-Identifier: Apache-2.0

cd code
if [ "${SKIP_HOOKS}" != "true" ]
then
  npm run git:pre-commit
  git update-index --again
fi