---
name: code-npm-deploy

on:
  pull_request:
    types: [closed]
    branches: ["main", "main-*"]
    paths: ["code/**", ".github/workflows/code**"]
  workflow_dispatch:
    inputs:
      BASELINE:
        description: "Baseline branch"
        required: true
        default: "main"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Container Apps
    runs-on: ubuntu-24.04
    environment: azure-production
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
      AZURE_ACR_NAME: "acrweavejsx0j187"
      AZURE_RESOURCE_GROUP: "cloudcotwo-rsg-weu1-pro-weavejs"
      AZURE_CONTAINER_ENVIRONMENT_NAME: "container-apps-env-weavejs-x0j187"
      AZURE_CONTAINER_NAME: "frontend-app-9"
      AZURE_CONTAINER_NAME_BACKEND: "backend-app-9"
      AZURE_IDENTITY_ID: ${{ secrets.AZURE_IDENTITY_ID }}
      BACKEND_ENDPOINT: "http://backend-app-9:8080"
      NEXT_PUBLIC_API_ENDPOINT: ${{ vars.NEXT_PUBLIC_API_ENDPOINT }}
      NEXT_PUBLIC_API_ENDPOINT_HUB_NAME: ${{ vars.NEXT_PUBLIC_API_ENDPOINT_HUB_NAME }}
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Get backend fqdn
        working-directory: code
        run: |
          ENDPOINT=$(az containerapp show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_CONTAINER_NAME_BACKEND }} --query properties.configuration.ingress.fqdn)
          echo "BACKEND_ENDPOINT=http://$(echo $ENDPOINT):8080" >> $GITHUB_ENV

      - name: Create .env.production file
        working-directory: code
        run: |
          touch .env.production
          echo NEXT_PUBLIC_API_ENDPOINT=${{ env.NEXT_PUBLIC_API_ENDPOINT }} >> .env.production
          echo NEXT_PUBLIC_API_ENDPOINT_HUB_NAME=${{ env.NEXT_PUBLIC_API_ENDPOINT_HUB_NAME }} >> .env.production
          echo BACKEND_ENDPOINT=${{ env.BACKEND_ENDPOINT }} >> .env.production
            cat .env.production

      - name: ACR Login
        run: |
          ACR_PASSWORD=$(az acr login --name ${{ env.AZURE_ACR_NAME }} --expose-token --output tsv --query accessToken)
          echo "AZURE_ACR_PASSWORD=$(echo $ACR_PASSWORD)" >> $GITHUB_ENV

      - name: ACR Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ env.AZURE_ACR_USERNAME }}
          password: ${{ env.AZURE_ACR_PASSWORD }}

      - name: Build image and push it to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          context: code
          tags: ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.AZURE_CONTAINER_NAME }}:${{ github.sha }}
          file: code/Dockerfile

      - name: Deploy
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp create \
              --name $AZURE_CONTAINER_NAME \
              --resource-group $AZURE_RESOURCE_GROUP \
              --environment $AZURE_CONTAINER_ENVIRONMENT_NAME \
              --image $AZURE_ACR_NAME.azurecr.io/$AZURE_CONTAINER_NAME:${{ github.sha }} \
              --target-port 8080 \
              --ingress external \
              --registry-server $AZURE_ACR_NAME.azurecr.io \
              --user-assigned "$AZURE_IDENTITY_ID" \
              --registry-identity "$AZURE_IDENTITY_ID" \
              --min-replicas 1 \
              --max-replicas 2 \
              --scale-rule-name http-rule \
              --scale-rule-type http \
              --scale-rule-http-concurrency 10 \
              --query properties.configuration.ingress.fqdn
